(()=>{
'use strict';
const HAPI='https://stock-truth-v2.vercel.app/api/horizon-model-v1';
let HM=null,HMSYM=null,HMERR=null,HMLOAD=false;
const hCache=new Map(),LEDGER_KEY='stocktruth:v3ledger';
const fin3=x=>x!==null&&x!==undefined&&Number.isFinite(Number(x));
const esc3=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const f3=(x,d=2)=>fin3(x)?Number(x).toLocaleString('en-US',{minimumFractionDigits:d,maximumFractionDigits:d}):'—';
const p3=(x,d=1)=>fin3(x)?`${(Number(x)*100).toFixed(d)}%`:'—';
function cls3(x){return String(x||'').includes('BULL')||String(x||'').includes('CONSTRUCT')||String(x||'')==='VERIFIED'?'up':String(x||'').includes('BEAR')||String(x||'').includes('CAUT')?'down':'amber';}
function loadLedger(){try{return JSON.parse(localStorage.getItem(LEDGER_KEY)||'[]');}catch{return[];}}
function saveLedger(a){try{localStorage.setItem(LEDGER_KEY,JSON.stringify(a.slice(-300)));}catch{}}
function histFor(h){return h==='4H'?HM?.history?.hourly:HM?.history?.daily;}
function barsFor(h){return h==='4H'?4:h==='1D'?1:h==='1W'?5:252;}
function resolveLedger(a){if(!HM)return a;for(const e of a){if(e.status!=='PENDING'||e.symbol!==HM.symbol)continue;const hist=histFor(e.horizon)||[],k=hist.findIndex(x=>Number(x.ts)===Number(e.start_ts));if(k>=0&&k+e.horizon_bars<hist.length){const z=hist[k+e.horizon_bars];e.status='RESOLVED';e.end_ts=z.ts;e.actual_price=z.close;e.actual_return=e.start_price?z.close/e.start_price-1:null;const actualUp=z.close>e.start_price,predUp=e.prob_up>=.5;e.correct=actualUp===predUp;}}return a;}
function recordLedger(){if(!HM)return;let a=resolveLedger(loadLedger());for(const h of HM.horizons||[]){if(!fin3(h.prob_up)||!fin3(h.current_price))continue;const hist=histFor(h.horizon)||[],last=hist.at(-1);if(!last)continue;const key=[HM.symbol,h.horizon,last.ts,h.model_version].join('|');if(a.some(x=>x.key===key))continue;a.push({key,symbol:HM.symbol,horizon:h.horizon,start_ts:last.ts,start_price:h.current_price,horizon_bars:barsFor(h.horizon),prob_up:h.prob_up,bias:h.bias,model_status:h.status,model_version:h.model_version,status:'PENDING',created_at:HM.generated_at});}saveLedger(a);}
async function loadHM(sym){if(!sym||HMLOAD)return;if(hCache.has(sym)){HM=hCache.get(sym);HMSYM=sym;HMERR=null;recordLedger();try{render();}catch{}return;}HMLOAD=true;HMSYM=sym;HMERR=null;try{const r=await fetch(`${HAPI}?symbol=${encodeURIComponent(sym)}`,{cache:'no-store'}),j=await r.json();if(!r.ok||j.error)throw new Error(j.error||`HTTP ${r.status}`);HM=j;hCache.set(sym,j);recordLedger();}catch(e){HM=null;HMERR=String(e?.message||e);}finally{HMLOAD=false;try{render();}catch{}}}
function horizonCards(){if(HMERR)return`<div class="panel"><h2>Multi-horizon model <span class="tag bad">UNAVAILABLE</span></h2><p class="note err">${esc3(HMERR)}</p></div>`;if(!HM||HMSYM!==D?.symbol)return`<div class="panel"><h2>Multi-horizon model <span class="tag pulse">CALCULATING</span></h2><p class="note">Training separate 4H, 1D, 1W and 1Y models from completed bars.</p></div>`;return`<div class="panel" style="border-color:rgba(155,135,196,.45)"><h2>Multi-horizon institutional model <span class="tag">SEPARATE MODELS · REGIME AWARE</span></h2><div class="grid g2">${HM.horizons.map(h=>{if(!fin3(h.prob_up))return`<div class="panel"><h3>${h.horizon}</h3><div class="amber">${esc3(h.status)}</div><p class="note">${esc3(h.reason||'Not enough history.')}</p></div>`;return`<div class="panel"><h3>${h.horizon} <span class="tag ${h.status==='VERIFIED'?'good':''}">${esc3(h.status)}</span></h3><div class="stats"><div class="st"><div class="l">Bias</div><div class="v ${cls3(h.bias)}">${esc3(h.bias)}</div></div><div class="st"><div class="l">Calibrated P(up)</div><div class="v">${p3(h.prob_up)}</div></div><div class="st"><div class="l">Base target</div><div class="v">$${f3(h.target)}</div></div><div class="st"><div class="l">Expected range</div><div class="v">$${f3(h.expected_low)} – $${f3(h.expected_high)}</div></div><div class="st"><div class="l">Invalidation</div><div class="v">$${f3(h.invalidation)}</div></div><div class="st"><div class="l">Regime</div><div class="v" style="font-size:12px">${esc3(h.regime)}</div><div class="s">${h.regime_specific?'same-regime validation':'broader-history fallback'}</div></div></div><p class="note">Bull / bear scenario: $${f3(h.bull_case)} / $${f3(h.bear_case)} · OOS edge ${p3(h.edge)} · independent samples ${h.independent_samples??'—'}.</p></div>`;}).join('')}</div><p class="note"><b>Truth rule:</b> VERIFIED means this horizon cleared the current out-of-sample gates. DEVELOPING/UNVERIFIED can still show a directional lean, but that lean is not promoted as a proven forecasting edge.</p></div>`;}
function avwap(b,start){if(start<0||start>=b.length)return Array(b.length).fill(null);let pv=0,v=0;return b.map((x,i)=>{if(i<start)return null;const vol=Number(x.volume)||0,tp=(x.high+x.low+x.close)/3;pv+=tp*vol;v+=vol;return v?pv/v:null;});}
function breakoutIndex(b){for(let i=b.length-1;i>=20&&i>=b.length-80;i--){const prev=Math.max(...b.slice(i-20,i).map(x=>x.high));if(b[i].close>prev)return i;}return -1;}
function workspaceData(){const all=D?.daily?.bars||[];if(all.length<40)return null;const b=all.slice(-140),yr=new Date(b.at(-1).date).getUTCFullYear(),ytd=Math.max(0,b.findIndex(x=>new Date(x.date).getUTCFullYear()===yr)),s0=Math.max(0,b.length-60),sw=s0+b.slice(s0).reduce((best,x,i,a)=>x.low<a[best].low?i:best,0),br=breakoutIndex(b),A=[{n:'YTD AVWAP',a:ytd,v:avwap(b,ytd)},{n:'Swing-low AVWAP',a:sw,v:avwap(b,sw)}];if(br>=0)A.push({n:'Breakout AVWAP',a:br,v:avwap(b,br)});const lo=Math.min(...b.map(x=>x.low)),hi=Math.max(...b.map(x=>x.high)),N=24,step=(hi-lo)/N||1,p=Array(N).fill(0);for(const x of b){const tp=(x.high+x.low+x.close)/3,k=Math.max(0,Math.min(N-1,Math.floor((tp-lo)/step)));p[k]+=Number(x.volume)||0;}const total=p.reduce((a,z)=>a+z,0),pi=p.indexOf(Math.max(...p));let l=pi,r=pi,sum=p[pi];while(total&&sum/total<.70&&(l>0||r<N-1)){const lv=l>0?p[l-1]:-1,rv=r<N-1?p[r+1]:-1;if(rv>=lv){r++;sum+=p[r];}else{l--;sum+=p[l];}}return{b,A,profile:{poc:lo+(pi+.5)*step,val:lo+l*step,vah:lo+(r+1)*step,bins:p,lo,step,total}};}
function workspacePanel(){const x=workspaceData();if(!x)return'';const last=x.b.at(-1),av=x.A.map(a=>{const z=a.v.at(-1);return`<div class="st"><div class="l">${a.n}</div><div class="v">$${f3(z)}</div><div class="s">price ${last.close>=z?'above':'below'}</div></div>`;}).join('');return`<div class="panel" style="border-color:rgba(122,155,196,.45)"><h2>Institutional chart workspace <span class="tag">CANDLES · VOLUME · AVWAP</span></h2><div class="stats">${av}<div class="st"><div class="l">Volume-profile POC</div><div class="v">$${f3(x.profile.poc)}</div><div class="s">daily-bar proxy</div></div><div class="st"><div class="l">70% value area</div><div class="v">$${f3(x.profile.val)} – $${f3(x.profile.vah)}</div><div class="s">VAL / VAH</div></div></div><div style="height:430px;margin-top:10px"><canvas id="cvInstV3"></canvas></div><p class="note">AVWAP uses reported bar volume. The volume profile is an approximation built from daily-bar typical prices; it is <b>not</b> exchange tick-by-tick volume-at-price or a live order book.</p></div>`;}
function drawWorkspace(){const cv=document.querySelector('#cvInstV3'),x=workspaceData();if(!cv||!x)return;const dpr=window.devicePixelRatio||1,w=Math.max(320,cv.clientWidth),h=430;cv.width=w*dpr;cv.height=h*dpr;const c=cv.getContext('2d');c.scale(dpr,dpr);const css=getComputedStyle(document.documentElement),ink=css.getPropertyValue('--ink').trim()||'#ddd',dim=css.getPropertyValue('--faint').trim()||'#777',up=css.getPropertyValue('--up').trim()||'#4caf7d',dn=css.getPropertyValue('--down').trim()||'#e05252',blue=css.getPropertyValue('--blue').trim()||'#7a9bc4',live=css.getPropertyValue('--live').trim()||'#e8a33d',vio=css.getPropertyValue('--violet').trim()||'#9b87c4';c.clearRect(0,0,w,h);const L=52,R=12,Tp=15,VH=90,B=24,priceBottom=h-VH-B,plotW=w-L-R,ys=[...x.b.flatMap(z=>[z.low,z.high]),...x.A.flatMap(a=>a.v.filter(fin3))],mn=Math.min(...ys),mx=Math.max(...ys),pad=(mx-mn)*.06||1,y=v=>Tp+(mx+pad-v)/(mx-mn+2*pad)*(priceBottom-Tp),cw=plotW/x.b.length;for(let g=0;g<5;g++){const yy=Tp+g*(priceBottom-Tp)/4;c.strokeStyle='rgba(140,144,154,.12)';c.beginPath();c.moveTo(L,yy);c.lineTo(w-R,yy);c.stroke();const val=mx+pad-g*(mx-mn+2*pad)/4;c.fillStyle=dim;c.font='10px monospace';c.fillText(f3(val,2),3,yy+3);}const vmax=Math.max(...x.b.map(z=>z.volume||0))||1;x.b.forEach((z,i)=>{const xx=L+(i+.5)*cw,clr=z.close>=z.open?up:dn;c.strokeStyle=clr;c.lineWidth=1;c.beginPath();c.moveTo(xx,y(z.high));c.lineTo(xx,y(z.low));c.stroke();c.fillStyle=clr;const y1=y(Math.max(z.open,z.close)),y2=y(Math.min(z.open,z.close));c.fillRect(xx-Math.max(1,cw*.28),y1,Math.max(2,cw*.56),Math.max(1,y2-y1));const vh=(z.volume||0)/vmax*(VH-18);c.globalAlpha=.35;c.fillRect(xx-Math.max(1,cw*.28),h-B-vh,Math.max(2,cw*.56),vh);c.globalAlpha=1;});const cols=[blue,live,vio];x.A.forEach((a,k)=>{c.strokeStyle=cols[k%cols.length];c.lineWidth=1.5;c.beginPath();let started=false;a.v.forEach((v,i)=>{if(!fin3(v))return;const xx=L+(i+.5)*cw,yy=y(v);if(!started){c.moveTo(xx,yy);started=true;}else c.lineTo(xx,yy);});c.stroke();});c.fillStyle=dim;c.font='10px monospace';for(let i=0;i<x.b.length;i+=Math.ceil(x.b.length/6)){c.fillText(String(x.b[i].date).slice(5,10),L+(i+.5)*cw-12,h-5);}c.fillStyle=blue;c.fillText('YTD AVWAP',L+5,Tp+10);c.fillStyle=live;c.fillText('Swing AVWAP',L+90,Tp+10);if(x.A.length>2){c.fillStyle=vio;c.fillText('Breakout AVWAP',L+190,Tp+10);}}
function modelLab(){if(HMERR)return horizonCards();if(!HM)return horizonCards();let led=resolveLedger(loadLedger());saveLedger(led);const mine=led.filter(x=>x.symbol===HM.symbol),resolved=mine.filter(x=>x.status==='RESOLVED'),acc=resolved.length?resolved.filter(x=>x.correct).length/resolved.length:null;return`${horizonCards()}<div class="panel"><h2>Model Lab <span class="tag">OOS VALIDATION</span></h2><table><tr><th>Horizon</th><th>Status</th><th>Regime</th><th>P(up)</th><th>OOS hit</th><th>Balanced</th><th>Baseline</th><th>Edge</th><th>Brier skill</th><th>Independent</th></tr>${(HM.horizons||[]).map(h=>`<tr><td>${h.horizon}</td><td class="${h.status==='VERIFIED'?'up':'amber'}">${esc3(h.status)}</td><td>${esc3(h.regime||'—')}${h.regime_specific?'':' *'}</td><td>${p3(h.prob_up)}</td><td>${p3(h.accuracy)}</td><td>${p3(h.balanced)}</td><td>${p3(h.baseline)}</td><td class="${fin3(h.edge)&&h.edge>0?'up':fin3(h.edge)&&h.edge<0?'down':''}">${p3(h.edge)}</td><td>${p3(h.brier_skill)}</td><td>${h.independent_samples??'—'}</td></tr>`).join('')}</table><p class="note">* insufficient same-regime sample, so the model used broader historical states and says so explicitly.</p></div><div class="panel"><h2>Prediction ledger <span class="tag">BROWSER-SAVED · PRE-OUTCOME</span></h2><div class="stats"><div class="st"><div class="l">Saved predictions</div><div class="v">${mine.length}</div></div><div class="st"><div class="l">Resolved</div><div class="v">${resolved.length}</div></div><div class="st"><div class="l">Resolved direction accuracy</div><div class="v">${p3(acc)}</div><div class="s">not a substitute for OOS validation</div></div></div><div style="overflow:auto"><table><tr><th>Horizon</th><th>Start</th><th>Bias</th><th>P(up)</th><th>Start price</th><th>Outcome</th><th>Correct?</th></tr>${mine.slice(-20).reverse().map(e=>`<tr><td>${e.horizon}</td><td>${new Date(e.start_ts*1000).toLocaleDateString()}</td><td>${esc3(e.bias)}</td><td>${p3(e.prob_up)}</td><td>$${f3(e.start_price)}</td><td>${e.status==='RESOLVED'?`$${f3(e.actual_price)} (${p3(e.actual_return)})`:'PENDING'}</td><td class="${e.status==='RESOLVED'?(e.correct?'up':'down'):'dim'}">${e.status==='RESOLVED'?(e.correct?'YES':'NO'):'—'}</td></tr>`).join('')}</table></div><p class="note">The ledger is written before the outcome and stored in this browser. It is an audit aid, not tamper-proof institutional storage. The OOS metrics above remain the primary validation evidence.</p></div>`;}
try{
  const baseTech=tabTech,baseVerdict=tabVerdict,baseRender=render;
  tabTech=function(){return workspacePanel()+baseTech();};
  tabVerdict=function(){return horizonCards()+baseVerdict();};
  render=function(){baseRender();const tabs=document.querySelector('.tabs');if(tabs&&!tabs.querySelector('[data-v3model]')){const b=document.createElement('button');b.textContent='MODEL LAB';b.dataset.v3model='1';b.className=TAB==='model'?'on':'';b.addEventListener('click',()=>{TAB='model';render();});tabs.appendChild(b);}if(tabs){const b=tabs.querySelector('[data-v3model]');if(b)b.classList.toggle('on',TAB==='model');}if(TAB==='model'&&tabs?.nextElementSibling)tabs.nextElementSibling.innerHTML=modelLab();if(TAB==='tech')requestAnimationFrame(drawWorkspace);};
}catch(e){console.warn('V3 upgrade patch failed',e);}
window.addEventListener('stocktruth:v2data',e=>{const s=e?.detail?.symbol;if(s&&s!==HMSYM)loadHM(s);});
try{const s=window.V2DATA?.symbol||(typeof D!=='undefined'&&D?.symbol);if(s)loadHM(s);}catch{}
})();
