import test from 'node:test';import assert from 'node:assert/strict';
import {buildBriefing} from '../quant/src/briefing.mjs';
const q={symbol:'TEST',timeframe:'1D',bars:[{close:100,end_ts:1}],state:{direction:'BULLISH',stage:'READY'},quote:{price:100},structure:{support:[{price:95}],resistance:[{price:110}]},plan:{entryZone:{low:98,high:100},trigger:103,stop:96,targets:[{price:101},{price:108},{price:115}]},forecast:{monteCarlo:[{step:10,p25:90,median:102,p75:115}]}};
const gate={allowed:true,quote:{allowed:true},historyStatus:'COMPLETED BAR'};
test('breakout excludes targets behind entry and calculates risk from that entry',()=>{const b=buildBriefing(q,gate),e=b.pathways.find(x=>x.name==='Breakout');assert.equal(e.targets.length,2);assert.equal(e.targets[0].riskReward,5/7);assert.equal(b.action,'WAIT — REWARD TOO SMALL');});
test('stale quote preserves timestamped planning but never recommends entry',()=>{const b=buildBriefing(q,{...gate,allowed:false,quote:{allowed:false}});assert.equal(b.action,'PLAN NOW · WAIT TO ENTER');assert.equal(b.range.mid,102);assert.equal(b.mode,'CANDLE-BASED PLAN · LIVE ENTRY BLOCKED');});
test('live price beyond target prevents chasing; invalidation overrides optimistic model',()=>{assert.equal(buildBriefing({...q,quote:{price:112}},gate).action,'DO NOT CHASE');assert.equal(buildBriefing({...q,quote:{price:94}},gate).action,'AVOID THIS SETUP');});
test('short target geometry reverses correctly',()=>{const s={...q,state:{direction:'BEARISH',stage:'WATCH'},plan:{entryZone:{low:101,high:103},trigger:98,stop:105,targets:[{price:100},{price:95},{price:90}]}};const e=buildBriefing(s,gate).pathways.find(x=>x.name==='Breakdown');assert.equal(e.targets.length,2);assert.equal(e.targets[0].riskReward,3/7);});
test('invalid history remains review-only even with fresh quotes',()=>assert.equal(buildBriefing(q,{...gate,allowed:false,historyStatus:'STALE'}).action,'WAIT — UPDATE HISTORY'));
