export const clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
export const finite=x=>Number.isFinite(x);
export const mean=a=>a.length?a.reduce((s,x)=>s+x,0)/a.length:null;
export function std(a){if(a.length<2)return null;const m=mean(a);return Math.sqrt(a.reduce((s,x)=>s+(x-m)**2,0)/(a.length-1));}
export function quantile(a,q){if(!a.length)return null;const x=[...a].sort((u,v)=>u-v),p=(x.length-1)*q,i=Math.floor(p),f=p-i;return x[i]+(x[Math.min(i+1,x.length-1)]-x[i])*f;}
export function ema(values,n){const k=2/(n+1),out=[];let e=null;for(const v of values){if(!finite(v)){out.push(null);continue;}e=e==null?v:e+k*(v-e);out.push(e);}return out;}
export function diff(values){return values.map((v,i)=>i&&finite(v)&&finite(values[i-1])?v-values[i-1]:null);}
export function zscore(values,n=20){const out=[];for(let i=0;i<values.length;i++){const w=values.slice(Math.max(0,i-n+1),i+1).filter(finite),s=std(w),m=mean(w);out.push(w.length>=Math.min(8,n)&&s>0?(values[i]-m)/s:null);}return out;}
export function linearSlope(y){const n=y.length;if(n<3)return null;const mx=(n-1)/2,my=mean(y);let num=0,den=0;for(let i=0;i<n;i++){num+=(i-mx)*(y[i]-my);den+=(i-mx)**2;}return den?num/den:null;}
export function shannonEntropy(values,bins=7){const x=values.filter(finite);if(x.length<12)return null;const s=std(x);if(!s||s===0)return 0;const m=mean(x),counts=Array(bins).fill(0);for(const v of x){const z=clamp((v-m)/(3*s),-1,1);const j=Math.min(bins-1,Math.floor((z+1)/2*bins));counts[j]++;}let h=0;for(const c of counts)if(c){const p=c/x.length;h-=p*Math.log(p);}return h/Math.log(bins);}
export function hurstExponent(logPrices){const x=logPrices.filter(finite);if(x.length<80)return null;const lags=[2,4,8,16,32].filter(l=>l<x.length/3),xs=[],ys=[];for(const lag of lags){const d=[];for(let i=lag;i<x.length;i++)d.push(x[i]-x[i-lag]);const s=std(d);if(s>0){xs.push(Math.log(lag));ys.push(Math.log(s));}}const h=linearSlopeByX(xs,ys);return finite(h)?clamp(h,0,1):null;}
function linearSlopeByX(x,y){if(x.length<2)return null;const mx=mean(x),my=mean(y);let num=0,den=0;for(let i=0;i<x.length;i++){num+=(x[i]-mx)*(y[i]-my);den+=(x[i]-mx)**2;}return den?num/den:null;}
export function dominantCycle(values,minPeriod=10,maxPeriod=80){const x=values.filter(finite);if(x.length<Math.max(64,minPeriod*3))return null;const n=Math.min(x.length,256),w=x.slice(-n),trend=linearSlope(w)||0,m=mean(w),d=w.map((v,i)=>v-(m+trend*(i-(n-1)/2)));let best=null;for(let p=minPeriod;p<=Math.min(maxPeriod,Math.floor(n/2));p++){const omega=2*Math.PI/p;let re=0,im=0;for(let i=0;i<n;i++){re+=d[i]*Math.cos(omega*i);im-=d[i]*Math.sin(omega*i);}const power=(re*re+im*im)/n;if(!best||power>best.power)best={period:p,power,phase:Math.atan2(im,re)};}return best;}
export function trueRange(bars){return bars.map((b,i)=>i?Math.max(b.high-b.low,Math.abs(b.high-bars[i-1].close),Math.abs(b.low-bars[i-1].close)):b.high-b.low);}
export function rollingMean(values,n){return values.map((_,i)=>mean(values.slice(Math.max(0,i-n+1),i+1).filter(finite)));}
export function realizedVol(logReturns,annualizer=252){const s=std(logReturns.filter(finite));return s==null?null:s*Math.sqrt(annualizer);}
export function parkinsonVol(bars,annualizer=252){const x=bars.map(b=>Math.log(b.high/b.low)**2).filter(finite);if(x.length<2)return null;return Math.sqrt(mean(x)/(4*Math.log(2))*annualizer);}
export function seeded(seed=1){let s=(seed>>>0)||1;return()=>{s=(1664525*s+1013904223)>>>0;return s/4294967296;};}
export function hashSeed(text=''){let h=2166136261;for(let i=0;i<text.length;i++){h^=text.charCodeAt(i);h=Math.imul(h,16777619);}return h>>>0;}
export function normal(rand){let u=0,v=0;while(!u)u=rand();while(!v)v=rand();return Math.sqrt(-2*Math.log(u))*Math.cos(2*Math.PI*v);}
export function monteCarlo({price,mu,sigma,steps=20,paths=1200,seed=1,jumpProb=.025,jumpScale=2.5}){if(!(price>0)||!finite(mu)||!finite(sigma))return null;const rand=seeded(seed),terminal=[],byStep=Array.from({length:steps},()=>[]);for(let p=0;p<paths;p++){let logp=Math.log(price);for(let s=0;s<steps;s++){let shock=normal(rand);if(rand()<jumpProb)shock+=normal(rand)*jumpScale;logp+=mu+sigma*shock;const px=Math.exp(logp);byStep[s].push(px);if(s===steps-1)terminal.push(px);}}return {steps:byStep.map((a,i)=>({step:i+1,p10:quantile(a,.1),p25:quantile(a,.25),median:quantile(a,.5),p75:quantile(a,.75),p90:quantile(a,.9)})),terminal};}
export function wilson(success,n,z=1.96){if(!n)return {low:null,high:null};const p=success/n,den=1+z*z/n,mid=(p+z*z/(2*n))/den,half=z*Math.sqrt((p*(1-p)+z*z/(4*n))/n)/den;return {low:Math.max(0,mid-half),high:Math.min(1,mid+half)};}
