import {retrieveTicker} from '../providers.mjs';

const PRODUCTS={GOLD:'GC',XAU:'GC',GC:'GC',SILVER:'SI',XAG:'SI',SI:'SI',OIL:'CL',WTI:'CL',CRUDE:'CL',CL:'CL',NATGAS:'NG',NATURALGAS:'NG',NG:'NG',COPPER:'HG',HG:'HG',CORN:'ZC',ZC:'ZC',WHEAT:'ZW',ZW:'ZW',SOYBEANS:'ZS',SOY:'ZS',ZS:'ZS',PLATINUM:'PL',PL:'PL',PALLADIUM:'PA',PA:'PA'};
export const commodityProducts=PRODUCTS;
const FUTURE_CONTRACT=/^[A-Z]{1,3}[FGHJKMNQUVXZ]\d{1,2}$/;
const clean=s=>String(s||'').trim().toUpperCase().replace(/\s+/g,'');
export function detectAsset(symbol,choice='AUTO'){if(choice&&choice!=='AUTO')return choice;const s=clean(symbol);return PRODUCTS[s]||FUTURE_CONTRACT.test(s)?'FUTURE':'STOCK';}
function datesFor(tf){const days={'15M':35,'1H':150,'4H':520,'1D':1600}[tf]||1600,to=new Date(),from=new Date(Date.now()-days*86400000);return {from:from.toISOString().slice(0,10),to:to.toISOString().slice(0,10)};}
function stockResolution(tf){return {'15M':[15,'minute'],'1H':[1,'hour'],'4H':[4,'hour'],'1D':[1,'day']}[tf]||[1,'day'];}
function futuresResolution(tf){return {'15M':'15min','1H':'1hour','4H':'1hour','1D':'1session'}[tf]||'1session';}
function barFromAgg(r,seconds){const ts=Math.floor(r.t/1000);return {ts,end_ts:ts+seconds,date:new Date(r.t).toISOString().slice(0,10),session:new Date(r.t).toISOString().slice(0,10),open:r.o,high:r.h,low:r.l,close:r.c,volume:Number.isFinite(r.v)?r.v:null,complete:true};}
function barFromFuture(r,seconds){const ns=Number(r.window_start),ts=ns>1e15?Math.floor(ns/1e9):Math.floor(ns/1000),date=r.session_end_date||new Date(ts*1000).toISOString().slice(0,10);return {ts,end_ts:ts+seconds,date,session:date,open:r.open,high:r.high,low:r.low,close:r.close,volume:Number.isFinite(r.volume)?r.volume:null,complete:true};}
async function getJson(url,signal){const r=await fetch(url,{cache:'no-store',credentials:'omit',signal:signal?AbortSignal.any([signal,AbortSignal.timeout(15000)]):AbortSignal.timeout(15000)});if(!r.ok)throw new Error(`HTTP ${r.status} from ${new URL(url).host}`);const j=await r.json();if(j?.status&&j.status!=='OK'&&j.status!=='DELAYED')throw new Error(j.error||j.message||j.status);return j;}
async function massiveStock(symbol,tf,key,signal){const [mult,span]=stockResolution(tf),{from,to}=datesFor(tf),seconds=span==='minute'?mult*60:span==='hour'?mult*3600:86400;let last;for(const host of ['https://api.massive.com','https://api.polygon.io']){try{const url=`${host}/v2/aggs/ticker/${encodeURIComponent(symbol)}/range/${mult}/${span}/${from}/${to}?adjusted=true&sort=asc&limit=50000&apiKey=${encodeURIComponent(key)}`;const j=await getJson(url,signal);const bars=(j.results||[]).map(r=>barFromAgg(r,seconds));if(bars.length<60)throw new Error('Too few bars returned');return {symbol,sourceSymbol:symbol,asset:'STOCK',timeframe:tf,bars,provider:host.includes('massive')?'Massive':'Polygon legacy host'};}catch(e){last=e;}}throw last||new Error('Massive/Polygon stock data unavailable');}
async function fmpDaily(symbol,key,signal){const url=`https://financialmodelingprep.com/stable/historical-price-eod/full?symbol=${encodeURIComponent(symbol)}&apikey=${encodeURIComponent(key)}`,j=await getJson(url,signal),rows=Array.isArray(j)?j:j.historical||j.data||[];const bars=rows.map(r=>{const date=r.date||r.timestamp?.slice?.(0,10);const ts=Date.parse(date+'T14:30:00Z')/1000;return {ts,end_ts:ts+23400,date,session:date,open:+r.open,high:+r.high,low:+r.low,close:+r.close,volume:Number.isFinite(+r.volume)?+r.volume:null,complete:true};}).filter(b=>Number.isFinite(b.close)).sort((a,b)=>a.ts-b.ts);if(bars.length<60)throw new Error('FMP returned too few bars');return {symbol,sourceSymbol:symbol,asset:'STOCK',timeframe:'1D',bars,provider:'FMP'};}
async function alpha(symbol,tf,key,signal){const interval={'15M':'15min','1H':'60min'}[tf];const fn=interval?'TIME_SERIES_INTRADAY':'TIME_SERIES_DAILY';const url=`https://www.alphavantage.co/query?function=${fn}&symbol=${encodeURIComponent(symbol)}${interval?`&interval=${interval}&outputsize=full`:'&outputsize=full'}&apikey=${encodeURIComponent(key)}`;const j=await getJson(url,signal);if(j.Note||j.Information||j['Error Message'])throw new Error(j.Note||j.Information||j['Error Message']);const keyName=Object.keys(j).find(k=>k.startsWith('Time Series'));const rows=j[keyName]||{};const seconds=interval?(interval==='15min'?900:3600):86400;const bars=Object.entries(rows).map(([date,r])=>{const ms=Date.parse(date.includes(' ')?date.replace(' ','T')+'-04:00':date+'T16:00:00-04:00');return {ts:Math.floor(ms/1000),end_ts:Math.floor(ms/1000)+seconds,date:date.slice(0,10),session:date.slice(0,10),open:+r['1. open'],high:+r['2. high'],low:+r['3. low'],close:+r['4. close'],volume:Number.isFinite(+r['5. volume'])?+r['5. volume']:null,complete:true};}).filter(b=>Number.isFinite(b.close)).sort((a,b)=>a.ts-b.ts);if(bars.length<60)throw new Error('Alpha Vantage returned too few bars');return {symbol,sourceSymbol:symbol,asset:'STOCK',timeframe:tf,bars,provider:'Alpha Vantage'};}
async function resolveFront(product,key,signal){if(FUTURE_CONTRACT.test(product))return product;const code=PRODUCTS[product]||product;const today=new Date().toISOString().slice(0,10);const url=`https://api.massive.com/futures/v1/contracts?product_code=${encodeURIComponent(code)}&active=true&limit=100&sort=last_trade_date.asc&apiKey=${encodeURIComponent(key)}`;const j=await getJson(url,signal),rows=(j.results||[]).filter(r=>r.ticker&&(!r.last_trade_date||r.last_trade_date>=today));if(!rows.length)throw new Error(`No active ${code} futures contract returned`);rows.sort((a,b)=>(a.days_to_maturity??9999)-(b.days_to_maturity??9999));return (rows.find(r=>(r.days_to_maturity??30)>5)||rows[0]).ticker;}
function resample4h(bars){const out=[];for(let i=0;i<bars.length;i+=4){const g=bars.slice(i,i+4);if(g.length<4)break;out.push({ts:g[0].ts,end_ts:g.at(-1).end_ts,date:g[0].date,session:g.at(-1).session,open:g[0].open,high:Math.max(...g.map(x=>x.high)),low:Math.min(...g.map(x=>x.low)),close:g.at(-1).close,volume:g.every(x=>Number.isFinite(x.volume))?g.reduce((s,x)=>s+x.volume,0):null,complete:true});}return out;}
async function massiveFuture(input,tf,key,signal){const sourceSymbol=await resolveFront(clean(input),key,signal),resolution=futuresResolution(tf),{from,to}=datesFor(tf);const url=`https://api.massive.com/futures/v1/aggs/${encodeURIComponent(sourceSymbol)}?resolution=${resolution}&window_start.gte=${from}&window_start.lte=${to}&limit=5000&sort=window_start.asc&apiKey=${encodeURIComponent(key)}`;const j=await getJson(url,signal),seconds=resolution==='15min'?900:resolution==='1hour'?3600:86400;let bars=(j.results||[]).map(r=>barFromFuture(r,seconds)).filter(b=>Number.isFinite(b.close));if(tf==='4H')bars=resample4h(bars);if(bars.length<60)throw new Error(`Massive futures returned ${bars.length} bars`);return {symbol:clean(input),sourceSymbol,asset:'FUTURE',timeframe:tf,bars,provider:'Massive Futures'};}
export async function loadQuantData({symbol,asset='AUTO',timeframe='1D',keys={},calendar,signal}){const s=clean(symbol),kind=detectAsset(s,asset),errors=[];if(kind==='FUTURE'){if(!keys.massive)throw new Error('Commodity/futures data requires a Massive/Polygon API key. Open API Keys and save it locally.');return massiveFuture(s,timeframe,keys.massive,signal);}if(keys.massive){try{return await massiveStock(s,timeframe,keys.massive,signal);}catch(e){errors.push('Massive/Polygon: '+e.message);}}if(timeframe==='1D'&&keys.fmp){try{return await fmpDaily(s,keys.fmp,signal);}catch(e){errors.push('FMP: '+e.message);}}if(['15M','1H','1D'].includes(timeframe)&&keys.alpha){try{return await alpha(s,timeframe,keys.alpha,signal);}catch(e){errors.push('Alpha Vantage: '+e.message);}}if(timeframe==='1D'&&calendar){try{const raw=await retrieveTicker(s,calendar,signal,{snapshotBase:'../../data/raw/'});const b=raw.timeframes?.['1D']?.bars||[];if(b.length>=60)return {symbol:s,sourceSymbol:s,asset:raw.security_type||'STOCK',timeframe:'1D',bars:b,provider:raw.timeframes['1D'].provider||raw.quote?.provider||'Stock Analysis public'};}catch(e){errors.push('Public daily fallback: '+e.message);}}throw new Error(`No usable ${timeframe} data for ${s}. ${errors.join(' | ')}${timeframe!=='1D'&&!keys.massive&&!keys.alpha?' Add a Massive/Polygon key for intraday data.':''}`);}
