"""Train Q-State 2.0 walk-forward calibrated directional models.

Inputs are sanitized OHLCV snapshots restored/generated by GitHub Actions.
Outputs contain coefficients, calibration curves and OOS conditional return bands.
No credentials are read or written here.
"""
from __future__ import annotations
import json, math, os
from pathlib import Path
from datetime import datetime, timezone

import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import brier_score_loss, log_loss

ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/'data'/'quant'/'model.json'
TIMEFRAMES=('15M','1H','4H','1D')
HORIZONS=(5,10,20)
FEATURES=(
    'ret1','ret5','ret20',
    'ema20_dist','ema50_dist','ema200_dist',
    'rsi_center','atr_pct','volume_z','compression',
    'range_pos20','breakout20',
    'latent_velocity','latent_acceleration',
    'realized_vol20','trend_state','trend_momentum',
    'compression_flag','meanrev_signal'
)

def now_iso(): return datetime.now(timezone.utc).isoformat()
def finite(x):
    try:return math.isfinite(float(x))
    except:return False
def safe_log(x): return math.log(x) if x and x>0 else np.nan

def ema(a,n):
    out=np.full(len(a),np.nan); k=2/(n+1); e=np.nan
    for i,v in enumerate(a):
        if not np.isfinite(v): continue
        e=v if not np.isfinite(e) else e+k*(v-e); out[i]=e
    return out

def rsi(a,n=14):
    out=np.full(len(a),np.nan)
    if len(a)<=n:return out
    d=np.diff(a); gains=np.maximum(d,0); losses=np.maximum(-d,0)
    g=float(np.mean(gains[:n])); l=float(np.mean(losses[:n]))
    out[n]=100 if l==0 else 100-100/(1+g/l)
    for i in range(n+1,len(a)):
        g=(g*(n-1)+gains[i-1])/n; l=(l*(n-1)+losses[i-1])/n
        out[i]=100 if l==0 else 100-100/(1+g/l)
    return out

def rolling_mean(a,n):
    out=np.full(len(a),np.nan)
    for i in range(n-1,len(a)):
        w=a[i-n+1:i+1]; w=w[np.isfinite(w)]
        if len(w)>=max(3,n//2):out[i]=float(np.mean(w))
    return out

def rolling_std(a,n):
    out=np.full(len(a),np.nan)
    for i in range(n-1,len(a)):
        w=a[i-n+1:i+1]; w=w[np.isfinite(w)]
        if len(w)>=max(5,n//2):out[i]=float(np.std(w,ddof=1))
    return out

def true_range(o,h,l,c):
    out=np.full(len(c),np.nan)
    for i in range(len(c)):
        out[i]=h[i]-l[i] if i==0 else max(h[i]-l[i],abs(h[i]-c[i-1]),abs(l[i]-c[i-1]))
    return out

def latent_filter(logp,alpha=.22,beta=.045):
    level=np.full(len(logp),np.nan); vel=np.full(len(logp),np.nan); acc=np.full(len(logp),np.nan)
    lv=np.nan; vv=0.0; prev_v=0.0
    for i,z in enumerate(logp):
        if not np.isfinite(z):continue
        if not np.isfinite(lv):
            lv=z; vv=0.0
        else:
            pred=lv+vv; err=z-pred; lv=pred+alpha*err; prev_v=vv; vv=vv+beta*err
        level[i]=lv; vel[i]=vv; acc[i]=vv-prev_v if i else 0.0
    return level,vel,acc

def block_features(bars):
    bars=sorted([b for b in bars if all(finite(b.get(k)) for k in ('open','high','low','close')) and float(b['close'])>0],key=lambda b:b.get('ts',0))
    if len(bars)<260:return None
    o=np.array([float(b['open']) for b in bars]);h=np.array([float(b['high']) for b in bars]);l=np.array([float(b['low']) for b in bars]);c=np.array([float(b['close']) for b in bars])
    v=np.array([float(b['volume']) if finite(b.get('volume')) else np.nan for b in bars])
    ts=np.array([int(b.get('ts') or b.get('end_ts') or i) for i,b in enumerate(bars)],dtype=np.int64)
    logp=np.log(c); ret=np.full(len(c),np.nan); ret[1:]=np.diff(logp)
    e20,e50,e200=ema(c,20),ema(c,50),ema(c,200); r=rsi(c,14)
    tr=true_range(o,h,l,c); atr14=rolling_mean(tr,14); atr50=rolling_mean(atr14,50)
    volm=rolling_mean(v,30); vols=rolling_std(v,30)
    volume_z=np.where((vols>0)&np.isfinite(v),(v-volm)/vols,np.nan)
    rv20=rolling_std(ret,20)
    _,latent_v,latent_a=latent_filter(logp)
    out=[]
    for i in range(210,len(c)):
        atr_pct=atr14[i]/c[i] if finite(atr14[i]) and c[i]>0 else np.nan
        hi20=float(np.max(h[i-20:i])); lo20=float(np.min(l[i-20:i])); width=hi20-lo20
        range_pos=((c[i]-lo20)/width*2-1) if width>0 else 0.0
        breakout=1.0 if c[i]>hi20 else -1.0 if c[i]<lo20 else 0.0
        trend=1.0 if e20[i]>e50[i] else -1.0 if e20[i]<e50[i] else 0.0
        comp=(atr14[i]/atr50[i]) if finite(atr14[i]) and finite(atr50[i]) and atr50[i]>0 else np.nan
        rcenter=(r[i]-50)/50 if finite(r[i]) else np.nan
        ret1=ret[i]; ret5=logp[i]-logp[i-5]; ret20=logp[i]-logp[i-20]
        meanrev=(-rcenter if finite(rcenter) and abs(rcenter)>.30 else 0.0)
        x=[
            ret1,ret5,ret20,
            c[i]/e20[i]-1 if e20[i]>0 else np.nan,
            c[i]/e50[i]-1 if e50[i]>0 else np.nan,
            c[i]/e200[i]-1 if e200[i]>0 else np.nan,
            rcenter,atr_pct,volume_z[i],comp-1 if finite(comp) else np.nan,
            range_pos,breakout,
            latent_v[i]/atr_pct if finite(latent_v[i]) and finite(atr_pct) and atr_pct>0 else np.nan,
            latent_a[i]/atr_pct if finite(latent_a[i]) and finite(atr_pct) and atr_pct>0 else np.nan,
            rv20[i],trend,trend*ret5,
            1.0 if finite(comp) and comp<.80 else 0.0,meanrev
        ]
        if all(finite(z) for z in x):
            out.append((i,ts[i],np.asarray(x,dtype=float)))
    return bars,c,logp,out

def load_blocks():
    blocks=[]
    raw=ROOT/'data'/'raw'
    if raw.exists():
        for p in sorted(raw.glob('*.json')):
            try:j=json.loads(p.read_text())
            except:continue
            for tf in TIMEFRAMES:
                b=(j.get('timeframes') or {}).get(tf,{}).get('bars') or []
                if len(b)>=260:blocks.append((p.stem,tf,b,'EQUITY'))
    qdir=ROOT/'data'/'quant'
    if qdir.exists():
        for p in sorted(qdir.glob('*.json')):
            if p.name in ('context.json','model.json'):continue
            try:j=json.loads(p.read_text())
            except:continue
            if j.get('asset')!='FUTURE':continue
            for tf in TIMEFRAMES:
                b=(j.get('timeframes') or {}).get(tf,{}).get('bars') or []
                if len(b)>=260:blocks.append((j.get('symbol') or p.stem,tf,b,'FUTURE'))
    return blocks

def datasets(blocks):
    by={tf:{h:[] for h in HORIZONS} for tf in TIMEFRAMES}
    assets=set(); symbols=set()
    for symbol,tf,bars,asset in blocks:
        bf=block_features(bars)
        if not bf:continue
        _,c,logp,rows=bf; symbols.add(symbol);assets.add(asset)
        for i,ts,x in rows:
            for hor in HORIZONS:
                if i+hor>=len(c):continue
                fr=float(logp[i+hor]-logp[i])
                by[tf][hor].append((int(ts),symbol,x,1 if fr>0 else 0,fr))
    return by,sorted(symbols),sorted(assets)

def chronological_folds(rows,nfold=5):
    if len(rows)<1200:return []
    rows=sorted(rows,key=lambda r:r[0]); times=np.array(sorted(set(r[0] for r in rows)),dtype=np.int64)
    if len(times)<300:return []
    folds=[]
    starts=np.linspace(.50,.82,nfold)
    width=.12
    for frac in starts:
        a=int(len(times)*frac); b=min(len(times),int(len(times)*(frac+width)))
        if a<80 or b-a<25:continue
        train_cut=times[max(0,a-20)]; test_lo=times[a]; test_hi=times[b-1]
        tr=[r for r in rows if r[0]<train_cut]; te=[r for r in rows if test_lo<=r[0]<=test_hi]
        if len(tr)>=600 and len(te)>=120:folds.append((tr,te))
    return folds

def fit_pipeline(rows):
    X=np.vstack([r[2] for r in rows]); y=np.asarray([r[3] for r in rows],dtype=int)
    scaler=StandardScaler().fit(X); Xs=scaler.transform(X)
    clf=LogisticRegression(C=.45,max_iter=2500,solver='lbfgs').fit(Xs,y)
    return scaler,clf

def calibrate_points(pred,y):
    pred=np.asarray(pred);y=np.asarray(y);points=[]
    edges=np.linspace(0,1,11)
    base=float(np.mean(y))
    for a,b in zip(edges[:-1],edges[1:]):
        mask=(pred>=a)&(pred<(b if b<1 else 1.000001));n=int(mask.sum())
        if n<35:continue
        raw=float(np.mean(pred[mask])); empirical=float((y[mask].sum()+8*base)/(n+8))
        points.append({'raw':raw,'calibrated':empirical,'n':n})
    return points

def return_bands(pred,rets):
    pred=np.asarray(pred);rets=np.asarray(rets);out=[];edges=np.linspace(0,1,11)
    for a,b in zip(edges[:-1],edges[1:]):
        mask=(pred>=a)&(pred<(b if b<1 else 1.000001));n=int(mask.sum())
        if n<35:continue
        q=np.quantile(rets[mask],[.10,.25,.50,.75,.90])
        out.append({'low':float(a),'high':float(b),'n':n,'q10':float(q[0]),'q25':float(q[1]),'q50':float(q[2]),'q75':float(q[3]),'q90':float(q[4])})
    return out

def train_one(rows):
    folds=chronological_folds(rows);oos_pred=[];oos_y=[];oos_ret=[];base_pred=[];fold_meta=[]
    for tr,te in folds:
        scaler,clf=fit_pipeline(tr)
        X=np.vstack([r[2] for r in te]);p=clf.predict_proba(scaler.transform(X))[:,1]
        y=np.asarray([r[3] for r in te]);rr=np.asarray([r[4] for r in te])
        bp=float(np.mean([r[3] for r in tr]))
        oos_pred.extend(p.tolist());oos_y.extend(y.tolist());oos_ret.extend(rr.tolist());base_pred.extend([bp]*len(te))
        fold_meta.append({'train_n':len(tr),'test_n':len(te),'train_base_rate':bp,'test_start':min(r[0] for r in te),'test_end':max(r[0] for r in te)})
    if len(oos_y)<400:
        return {'status':'INSUFFICIENT_OOS','samples':len(rows),'oos_samples':len(oos_y),'folds':len(folds)}
    op=np.asarray(oos_pred);oy=np.asarray(oos_y);bp=np.asarray(base_pred)
    brier=float(brier_score_loss(oy,op));base_brier=float(brier_score_loss(oy,bp))
    ll=float(log_loss(oy,np.clip(op,1e-6,1-1e-6)));base_ll=float(log_loss(oy,np.clip(bp,1e-6,1-1e-6)))
    skill=(base_brier-brier)/base_brier if base_brier>0 else 0.0
    validated=bool(len(folds)>=3 and len(oos_y)>=500 and skill>=.005 and ll<=base_ll)
    scaler,clf=fit_pipeline(rows)
    coef=clf.coef_[0]
    return {
      'status':'VALIDATED' if validated else 'NOT_VALIDATED',
      'validated':validated,'samples':len(rows),'oos_samples':len(oos_y),'folds':len(folds),
      'metrics':{'brier':brier,'base_brier':base_brier,'brier_skill':skill,'log_loss':ll,'base_log_loss':base_ll,'oos_base_rate':float(np.mean(oy))},
      'scaler':{'mean':scaler.mean_.tolist(),'scale':scaler.scale_.tolist()},
      'intercept':float(clf.intercept_[0]),'coef':coef.tolist(),
      'calibration':calibrate_points(op,oy),
      'return_bands':return_bands(op,np.asarray(oos_ret)),
      'folds_detail':fold_meta
    }

def main():
    blocks=load_blocks();by,symbols,assets=datasets(blocks)
    models={};summary={}
    for tf in TIMEFRAMES:
        models[tf]={};summary[tf]={}
        for hor in HORIZONS:
            rows=by[tf][hor]
            try:m=train_one(rows) if rows else {'status':'NO_DATA','samples':0,'oos_samples':0,'folds':0}
            except Exception as e:m={'status':'TRAINING_ERROR','samples':len(rows),'error':str(e)[:240]}
            models[tf][str(hor)]=m
            summary[tf][str(hor)]={'status':m.get('status'),'samples':m.get('samples',0),'oos_samples':m.get('oos_samples',0),'brier_skill':(m.get('metrics') or {}).get('brier_skill')}
            print(f"Q2 train {tf} h{hor}: {m.get('status')} samples={m.get('samples',0)} oos={m.get('oos_samples',0)}",flush=True)
    out={
      'schema_version':2,'model_version':'QSTATE-2.0-CALIBRATED','generated_at':now_iso(),
      'features':list(FEATURES),'timeframes':models,'summary':summary,
      'training':{'symbols':symbols,'asset_classes':assets,'blocks':len(blocks),'validation':'expanding chronological walk-forward with embargo; calibration and return bands use OOS predictions only'},
      'promotion_rule':'Probability is displayable only when OOS Brier skill >= 0.5%, log loss is no worse than base rate, >=3 folds and >=500 OOS samples.',
      'credential_policy':'Model trained only from sanitized snapshots; no credential is read or written by this script.'
    }
    OUT.parent.mkdir(parents=True,exist_ok=True);OUT.write_text(json.dumps(out,separators=(',',':'),allow_nan=False))
    print('Q-State 2.0 model written:',OUT)

if __name__=='__main__':main()
