import {createChart,CandlestickSeries,HistogramSeries,createSeriesMarkers} from '../../vendor/lightweight-charts.mjs';
import {loadQuantData,detectAsset} from '../../src/quant/providers.mjs';
import {quantAnalyze} from '../../src/quant/engine.mjs';
const $=s=>document.querySelector(s),finite=Number.isFinite,esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),fmt=(x,n=2)=>finite(x)?x.toFixed(n):'—',pct=x=>finite(x)?(x*100).toFixed(1)+'%':'—',money=x=>finite(x)?'$'+x.toLocaleString(undefined,{maximumFractionDigits:2,minimumFractionDigits:2}):'—';
let calendar=null,chart=null,controller=null;
try{calendar=await fetch('../../data/calendar.json',{cache:'no-store'}).then(r=>r.ok?r.json():null);}catch{}
function metric(label,value,klass=''){return `<div class="metric"><div class="label">${esc(label)}</div><div class="value ${klass}">${value}</div></div>`;}
function kv(label,value,klass=''){return `<div class="kv"><span>${esc(label)}</span><span class="${klass}">${value}</span></div>`;}
function pathCard(title,p,klass=''){return `<div class="path-card ${klass}"><b>${esc(title)}</b>${p?`<div class="path-values"><span>5 bars <strong>${money(p.bar5)}</strong></span><span>10 bars <strong>${money(p.bar10)}</strong></span><span>20 bars <strong>${money(p.bar20)}</strong></span></div>`:''}</div>`;}
function renderChart(q){
  if(chart)chart.remove();const host=$('#chart');host.innerHTML='';
  chart=createChart(host,{autoSize:true,layout:{background:{color:'#15191f'},textColor:'#9ca8b3',attributionLogo:true},grid:{vertLines:{color:'#20262d'},horzLines:{color:'#20262d'}},rightPriceScale:{borderColor:'#34404a'},timeScale:{borderColor:'#34404a',timeVisible:q.timeframe!=='1D'}});
  const bars=q.bars,time=b=>q.timeframe==='1D'?b.date:b.ts,c=chart.addSeries(CandlestickSeries,{upColor:'#5cc58f',downColor:'#ef7474',borderVisible:false,wickUpColor:'#5cc58f',wickDownColor:'#ef7474'});
  c.setData(bars.map(b=>({time:time(b),open:b.open,high:b.high,low:b.low,close:b.close})));
  const vol=chart.addSeries(HistogramSeries,{priceScaleId:'v',priceFormat:{type:'volume'}});vol.priceScale().applyOptions({scaleMargins:{top:.86,bottom:0}});
  vol.setData(bars.filter(b=>finite(b.volume)).map(b=>({time:time(b),value:b.volume,color:b.close>=b.open?'#315846':'#5b373b'})));
  const add=(p,title,color)=>{if(finite(p))c.createPriceLine({price:p,title,color,lineStyle:2,lineWidth:1,axisLabelVisible:true});};
  if(q.plan){
    add(q.plan.stop,'STOP / INVALIDATION','#ef7474');add(q.plan.entryZone.low,'ENTRY LOW','#e9ad55');add(q.plan.entryZone.high,'ENTRY HIGH','#e9ad55');add(q.plan.breakoutTrigger,q.plan.direction==='LONG'?'BREAKOUT TRIGGER':'BREAKDOWN TRIGGER','#c99bec');
    q.plan.targets.forEach((t,i)=>add(t.price,t.name,['#76b6e8','#69cfa2','#b7d98a'][i]||'#7cb4e8'));
  }
  const marks=[];for(const e of (q.frame.events||[]).slice(-14)){if(!['BOS','CHoCH','LIQUIDITY SWEEP'].includes(e.type)||!bars[e.i])continue;marks.push({time:time(bars[e.i]),position:e.dir>0?'belowBar':'aboveBar',shape:e.dir>0?'arrowUp':'arrowDown',color:e.dir>0?'#5cc58f':'#ef7474',text:e.type,size:.45});}
  marks.sort((a,b)=>a.time<b.time?-1:1);createSeriesMarkers(c,marks);chart.timeScale().setVisibleLogicalRange({from:Math.max(0,bars.length-150),to:bars.length+4});
  $('#chart-note').textContent=`${q.sourceSymbol} · ${q.timeframe} · ${bars.length.toLocaleString()} completed bars · ${q.provider}`;
}
function render(q){
  const d=q.state.direction,klass=d==='BULLISH'?'up':d==='BEARISH'?'down':'amber',last=q.bars.at(-1).close,p=q.plan;
  $('#hero').innerHTML=`<div>${metric(q.symbol,`${money(last)} <span class="${klass}">${d}</span>`)}<div class="note">${esc(q.asset)} · source symbol ${esc(q.sourceSymbol)}</div></div>${metric('Regime',esc(q.state.regime),klass)}${metric('Quant conviction',q.state.conviction+'/100',klass)}${metric('Signal stage',esc(q.state.signalStage),q.state.signalStage==='READY'?'up':q.state.signalStage==='DEVELOPING'?'amber':'')}${metric('Data source',esc(q.provider))}`;
  $('#decision').innerHTML=`<div><h2>Model action</h2><div class="decision-action ${klass}">${esc(q.state.action)}</div><div class="decision-meta"><span class="tag">QUALITY ${esc(q.state.quality)}</span><span class="tag">${esc(q.timeframe)} MODEL</span></div></div><div><h2>What the model says to do</h2><p class="decision-copy">${esc(p?.actionDetail||'No trade until the directional edge improves.')}</p>${p?`<p class="note"><b>Confirmation:</b> ${esc(p.entryRule)}<br><b>Invalidation:</b> ${esc(p.invalidation)}</p>`:''}</div>`;
  $('#source').textContent=q.provider;
  $('#plan').innerHTML=`<h2>Trade map</h2>${p?kv('Direction',p.direction,klass)+kv('Preferred entry',money(p.entryZone.low)+' – '+money(p.entryZone.high))+kv(p.direction==='LONG'?'Breakout trigger':'Breakdown trigger',money(p.breakoutTrigger),'amber')+kv('Fixed stop',money(p.stop),'down')+p.targets.map(t=>kv(t.name,money(t.price)+' · '+(finite(t.riskReward)?fmt(t.riskReward,2)+'R':'—'),'up')).join('')+kv('Nearest target R:R',finite(p.rr)?fmt(p.rr,2)+'R':'—')+`<p class="note">${esc(p.entryRule)}</p>`:'<p class="note">No trade map while the directional model is neutral.</p>'}`;
  const proj=q.forecast.projection;
  $('#projection').innerHTML=`<div class="section-title"><h2>Projected paths</h2><span class="tag">5 / 10 / 20 BARS</span></div>${proj?`<div class="projection-grid">${pathCard(proj.primary.label,proj.primary,klass)}${pathCard(proj.pullback.label,proj.pullback,'amber')}${pathCard(proj.expansion.label,proj.expansion,klass)}<div class="path-card down"><b>${esc(proj.failure.label)}</b><div class="failure-price">${money(proj.failure.price)}</div><p>${esc(proj.failure.note)}</p></div></div><div class="range-strip">${kv('10-bar central range',money(proj.range10?.low)+' – '+money(proj.range10?.high))}${kv('10-bar tail range',money(proj.range10?.tailLow)+' – '+money(proj.range10?.tailHigh))}${kv('20-bar central range',money(proj.range20?.low)+' – '+money(proj.range20?.high))}${kv('20-bar tail range',money(proj.range20?.tailLow)+' – '+money(proj.range20?.tailHigh))}</div><p class="note">Primary path is the model median. Pullback and expansion paths use distribution bands. These are scenario projections, not promised future prices.</p>`:'<p class="note">No directional projection while the model state is neutral.</p>'}`;
  const m=q.math;$('#metrics').innerHTML=[['Momentum physics',kv('Velocity',fmt(m.velocity))+kv('Acceleration',fmt(m.acceleration))+kv('Jerk',fmt(m.jerk))+kv('Curvature',fmt(m.curvature,5))],['Market state',kv('Entropy',fmt(m.entropy,3))+kv('Hurst exponent',fmt(m.hurst,3))+kv('Compression ratio',fmt(m.compression,2))+kv('Volume Z-score',fmt(m.volumeZ,2))],['Cycles + volatility',kv('Dominant cycle',m.dominantCycle?m.dominantCycle.period+' bars':'—')+kv('Cycle phase',m.dominantCycle?fmt(m.dominantCycle.phase*180/Math.PI,0)+'°':'—')+kv('Realized vol',pct(m.realizedVol))+kv('Parkinson vol',pct(m.parkinsonVol))]].map(([h,b])=>`<div class="panel"><h2>${h}</h2>${b}</div>`).join('');
  const steps=q.forecast.monteCarlo.filter(x=>[1,5,10,20].includes(x.step));$('#forecast').innerHTML=steps.length?`<table class="forecast-table"><thead><tr><th>Bars ahead</th><th>P10</th><th>P25</th><th>Median</th><th>P75</th><th>P90</th></tr></thead><tbody>${steps.map(x=>`<tr><td>${x.step}</td><td>${money(x.p10)}</td><td>${money(x.p25)}</td><td>${money(x.median)}</td><td>${money(x.p75)}</td><td>${money(x.p90)}</td></tr>`).join('')}</tbody></table><p class="note">Distribution uses 1,600 deterministic regime-conditioned paths. Percentiles are model estimates; they are not calibrated outcome probabilities.</p>`:'<p class="note">Insufficient data for forecast distribution.</p>';
  const c=q.forecast.calibration;$('#explain').innerHTML=`<div class="evidence"><div class="card"><b>Structure</b><p>${esc(q.frame.technicals?.intermediate_trend||'Unavailable')} trend; ${esc(q.frame.structure?.pattern||'structure unavailable')}. Recent structural breaks and sweeps are drawn on the chart.</p></div><div class="card"><b>Flow proxy</b><p>${m.bullAbsorption?'Bullish absorption proxy detected.':m.bearAbsorption?'Bearish absorption proxy detected.':'No strong absorption proxy on the latest completed bar.'}</p></div><div class="card"><b>Historical context</b><p>${c.n?`${(c.rate*100).toFixed(1)}% of ${c.n} comparable simplified historical states moved in the same direction over ${c.horizon} bars; 95% Wilson interval ${pct(c.interval.low)}–${pct(c.interval.high)}.`:'Not enough comparable historical states yet.'} Retrospective context is not an untouched out-of-sample probability.</p></div></div>`;
  $('#integrity').innerHTML=`${kv('Asset detected',esc(q.asset))}${kv('Requested symbol',esc(q.symbol))}${kv('Actual source symbol',esc(q.sourceSymbol))}${kv('Bars used',q.bars.length.toLocaleString())}${kv('Model',esc(q.model))}${kv('Data fetched',q.fetchedAt?new Date(q.fetchedAt).toLocaleString():'—')}${kv('Credential handling',esc(q.credentialPolicy||'No browser secret'))}${kv('Probability policy','No fabricated probability')}<p class="note">${esc(q.caveats.join(' '))}</p>`;
  renderChart(q);
}
async function run(){
  const symbol=$('#symbol').value.trim().toUpperCase();if(!symbol)return;controller?.abort();controller=new AbortController();$('#status').textContent='Loading sanitized market data and running quant engine…';
  try{const asset=detectAsset(symbol,$('#asset').value),tf=$('#tf').value,data=await loadQuantData({symbol,asset,timeframe:tf,calendar,signal:controller.signal});const q=quantAnalyze({...data});render(q);$('#status').textContent=`Ready · ${data.provider} · ${data.bars.length.toLocaleString()} completed bars`;history.replaceState(null,'',`?symbol=${encodeURIComponent(symbol)}&tf=${tf}&asset=${asset}`);}
  catch(e){if(e.name==='AbortError')return;$('#status').textContent='ERROR · '+e.message;$('#hero').innerHTML=`<div class="note">${esc(e.message)}</div>`;$('#decision').innerHTML='<div class="decision-action amber">WAIT — DATA UNAVAILABLE</div>';$('#chart').innerHTML='<div class="empty">No chart until valid sourced data is available.</div>';$('#plan').innerHTML='';$('#projection').innerHTML='';}
}
$('#form').onsubmit=e=>{e.preventDefault();run();};$('#tf').onchange=()=>run();const p=new URLSearchParams(location.search);if(p.get('symbol'))$('#symbol').value=p.get('symbol').toUpperCase();if(p.get('tf'))$('#tf').value=p.get('tf');if(p.get('asset'))$('#asset').value=p.get('asset');run();
