const UA='Mozilla/5.0 StockTruthV2/6.0 quarterly-research';
let SESSION=null;
function send(res,status,obj){res.statusCode=status;res.setHeader('Content-Type','application/json; charset=utf-8');res.setHeader('Access-Control-Allow-Origin','*');res.setHeader('Cache-Control',status===200?'s-maxage=1800, stale-while-revalidate=7200':'no-store');res.setHeader('X-Content-Type-Options','nosniff');res.end(JSON.stringify(obj));}
function clean(raw){const s=String(raw||'').trim().toUpperCase();return /^[A-Z0-9.^=-]{1,20}$/.test(s)?s:null;}
function num(v){if(v==null)return null;if(typeof v==='object'&&v.raw!=null)v=v.raw;const x=Number(v);return Number.isFinite(x)?x:null;}
function cookieFrom(r){try{const a=r.headers.getSetCookie?.();if(Array.isArray(a)&&a.length)return a.map(x=>x.split(';')[0]).join('; ');}catch{}const s=r.headers.get('set-cookie');if(!s)return'';return s.split(/,(?=[^;,]+=)/).map(x=>x.split(';')[0]).join('; ');}
async function session(){if(SESSION&&Date.now()-SESSION.at<20*60e3)return SESSION;let cookie='';for(const u of ['https://fc.yahoo.com/','https://finance.yahoo.com/']){try{const r=await fetch(u,{headers:{'User-Agent':UA,'Accept':'text/html,*/*'},redirect:'manual',cache:'no-store'});cookie=cookieFrom(r)||cookie;if(cookie)break;}catch{}}let crumb='';for(const host of ['query1.finance.yahoo.com','query2.finance.yahoo.com']){try{const r=await fetch(`https://${host}/v1/test/getcrumb`,{headers:{'User-Agent':UA,'Accept':'text/plain,*/*',...(cookie?{'Cookie':cookie}:{})},cache:'no-store'});cookie=cookieFrom(r)||cookie;if(r.ok){const t=(await r.text()).trim();if(t&&!t.startsWith('<')&&t.length<200){crumb=t;break;}}}catch{}}SESSION={cookie,crumb,at:Date.now()};return SESSION;}
async function getJson(url){let r=await fetch(url,{headers:{'User-Agent':UA,'Accept':'application/json'},cache:'no-store'});if(r.ok)return r.json();if(![401,403,429].includes(r.status))throw new Error(`Yahoo fundamentals returned HTTP ${r.status}`);const s=await session(),u=new URL(url);if(s.crumb)u.searchParams.set('crumb',s.crumb);r=await fetch(u.toString(),{headers:{'User-Agent':UA,'Accept':'application/json',...(s.cookie?{'Cookie':s.cookie}:{})},cache:'no-store'});if(!r.ok)throw new Error(`Yahoo fundamentals returned HTTP ${r.status}`);return r.json();}
const TYPES={
 quarterlyTotalRevenue:'revenue',quarterlyGrossProfit:'gross_profit',quarterlyOperatingIncome:'operating_income',quarterlyNetIncome:'net_income',quarterlyDilutedEPS:'eps',quarterlyOperatingCashFlow:'ocf',quarterlyCapitalExpenditure:'capex',quarterlyFreeCashFlow:'fcf',quarterlyCashCashEquivalentsAndShortTermInvestments:'cash',quarterlyLongTermDebt:'long_term_debt',quarterlyCurrentDebt:'current_debt',quarterlyStockholdersEquity:'equity',quarterlyTotalAssets:'assets',quarterlyCurrentAssets:'current_assets',quarterlyCurrentLiabilities:'current_liabilities',quarterlyDilutedAverageShares:'shares',quarterlyMarketCap:'market_cap',quarterlyPeRatio:'pe',quarterlyPbRatio:'pb',quarterlyPsRatio:'ps',quarterlyEbitda:'ebitda',quarterlyResearchAndDevelopment:'rd',quarterlyStockBasedCompensation:'sbc'
};
function quarterLabel(d){const x=new Date(d+'T00:00:00Z'),q=Math.floor(x.getUTCMonth()/3)+1;return `${x.getUTCFullYear()} Q${q}`;}
function add(map,date,key,value,currency){if(!date||value==null)return;let r=map.get(date);if(!r){r={date,label:quarterLabel(date),currency:currency||null};map.set(date,r);}r[key]=value;if(!r.currency&&currency)r.currency=currency;}
function extract(j){const out=new Map(),result=j?.timeseries?.result||[];for(const item of result){for(const [type,key] of Object.entries(TYPES)){const arr=item?.[type];if(!Array.isArray(arr))continue;for(const p of arr){const date=p.asOfDate||p.date||null,val=num(p.reportedValue??p.value);add(out,date,key,val,p.currencyCode||p.currency||null);}}}const rows=[...out.values()].sort((a,b)=>String(a.date).localeCompare(String(b.date))).slice(-10);for(const r of rows){const rev=num(r.revenue),gp=num(r.gross_profit),op=num(r.operating_income),ni=num(r.net_income),fcf=num(r.fcf),eq=num(r.equity),ca=num(r.current_assets),cl=num(r.current_liabilities),ld=num(r.long_term_debt)||0,cd=num(r.current_debt)||0;r.total_debt=(r.long_term_debt!=null||r.current_debt!=null)?ld+cd:null;r.gross_margin=rev&&gp!=null?gp/rev:null;r.op_margin=rev&&op!=null?op/rev:null;r.net_margin=rev&&ni!=null?ni/rev:null;r.fcf_margin=rev&&fcf!=null?fcf/rev:null;r.current_ratio=ca!=null&&cl?ca/cl:null;r.debt_to_equity=r.total_debt!=null&&eq?r.total_debt/eq:null;r.roe_annualized=ni!=null&&eq?ni*4/eq:null;}return rows;}
module.exports=async function handler(req,res){if(req.method==='OPTIONS')return send(res,200,{ok:true});if(req.method!=='GET')return send(res,405,{error:'GET only'});const symbol=clean(req.query?.symbol);if(!symbol)return send(res,400,{error:'Enter a valid ticker symbol.'});try{const u=new URL(`https://query1.finance.yahoo.com/ws/fundamentals-timeseries/v1/finance/timeseries/${encodeURIComponent(symbol)}`);u.searchParams.set('symbol',symbol);const now=Math.floor(Date.now()/1000),start=now-4*366*86400;u.searchParams.set('period1',String(start));u.searchParams.set('period2',String(now+86400));for(const t of Object.keys(TYPES))u.searchParams.append('type',t);const j=await getJson(u.toString());const rows=extract(j);if(!rows.length)return send(res,404,{symbol,error:'No quarterly fundamentals were returned for this security.',source:'yahoo-fundamentals-timeseries-server'});const fields=Object.values(TYPES),coverage=Object.fromEntries(fields.map(k=>[k,rows.filter(r=>r[k]!=null).length]));return send(res,200,{schema_version:1,symbol,generated_at:new Date().toISOString(),source:'yahoo-fundamentals-timeseries-server',quarters:rows.length,rows,coverage,note:'Quarterly statement series. Missing values remain unavailable; derived margins/ratios are calculated only when the required reported fields exist.'});}catch(e){return send(res,502,{symbol,source:'yahoo-fundamentals-timeseries-server',error:String(e?.message||e)});}};