const UA='Mozilla/5.0 StockTruthV3.2 split-price-technicals';
function send(res,status,obj){res.statusCode=status;res.setHeader('Content-Type','application/json; charset=utf-8');res.setHeader('Access-Control-Allow-Origin','*');res.setHeader('Cache-Control',status===200?'s-maxage=120, stale-while-revalidate=300':'no-store');res.setHeader('X-Content-Type-Options','nosniff');res.end(JSON.stringify(obj));}
const clean=s=>{s=String(s||'').trim().toUpperCase();return /^[A-Z0-9.^=-]{1,20}$/.test(s)?s:null;};
const TF={
  '1day':{interval:'1d',range:'max',seconds:86400,daily:true},
  '1h':{interval:'60m',range:'2y',seconds:3600},
  '30min':{interval:'30m',range:'60d',seconds:1800},
  '15min':{interval:'15m',range:'60d',seconds:900},
  '5min':{interval:'5m',range:'60d',seconds:300}
};
async function chart(symbol,cfg){const u=new URL(`https://query1.finance.yahoo.com/v8/finance/chart/${encodeURIComponent(symbol)}`);u.searchParams.set('range',cfg.range);u.searchParams.set('interval',cfg.interval);u.searchParams.set('includeAdjustedClose','false');u.searchParams.set('includePrePost','false');u.searchParams.set('events','splits');const r=await fetch(u,{headers:{'User-Agent':UA,'Accept':'application/json'},cache:'no-store'});if(!r.ok)throw new Error(`Yahoo chart ${cfg.interval} HTTP ${r.status}`);const j=await r.json(),x=j?.chart?.result?.[0];if(!x)throw new Error(j?.chart?.error?.description||'ticker not found');return x;}
function nyDate(sec){const p=new Intl.DateTimeFormat('en-CA',{timeZone:'America/New_York',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date(sec*1000));const m=Object.fromEntries(p.filter(x=>x.type!=='literal').map(x=>[x.type,x.value]));return `${m.year}-${m.month}-${m.day}`;}
function splits(x){return Object.values(x?.events?.splits||{}).map(z=>{let ratio=Number(z.numerator)/Number(z.denominator);if(!Number.isFinite(ratio)||ratio<=0){const m=String(z.splitRatio||'').match(/([0-9.]+)\s*:\s*([0-9.]+)/);ratio=m&&Number(m[2])?Number(m[1])/Number(m[2]):1;}return{ts:Number(z.date),ratio};}).filter(z=>Number.isFinite(z.ts)&&Number.isFinite(z.ratio)&&z.ratio>0).sort((a,b)=>a.ts-b.ts);}
function bars(x,cfg){const ts=x.timestamp||[],q=x.indicators?.quote?.[0]||{},ss=splits(x),out=[];for(let i=0;i<ts.length;i++){const o=Number(q.open?.[i]),h=Number(q.high?.[i]),l=Number(q.low?.[i]),c=Number(q.close?.[i]),v=Number(q.volume?.[i]),t=Number(ts[i]);if(![o,h,l,c,t].every(Number.isFinite)||c<=0)continue;let ratio=1;for(const s of ss)if(s.ts>t)ratio*=s.ratio;const pf=1/ratio;out.push({date:cfg.daily?nyDate(t):new Date(t*1000).toISOString(),open:o*pf,high:h*pf,low:l*pf,close:c*pf,volume:Number.isFinite(v)&&v>=0?v*ratio:null,ts:t});}
  if(out.length){const now=Math.floor(Date.now()/1000),last=out.at(-1),reg=x?.meta?.currentTradingPeriod?.regular||{};if(cfg.daily){if(reg.start&&reg.end&&now>=Number(reg.start)&&now<Number(reg.end)+900&&last.date===nyDate(now))out.pop();}else if(now<last.ts+cfg.seconds+45)out.pop();}
  return out.map(({ts,...z})=>z);
}
module.exports=async function handler(req,res){if(req.method==='OPTIONS')return send(res,200,{ok:true});if(req.method!=='GET')return send(res,405,{error:'GET only'});const symbol=clean(req.query?.symbol),tf=String(req.query?.tf||'1day');if(!symbol)return send(res,400,{error:'Enter a valid ticker.'});if(!TF[tf])return send(res,400,{error:'Supported timeframes: 1day, 1h, 30min, 15min, 5min.'});try{const cfg=TF[tf],[selR,dayR]=await Promise.all([chart(symbol,cfg),cfg.daily?Promise.resolve(null):chart(symbol,TF['1day'])]),selected=bars(selR,cfg),daily=cfg.daily?selected:bars(dayR,TF['1day']);if(selected.length<60)return send(res,422,{symbol,tf,error:`Only ${selected.length} completed ${tf} bars available.`});if(daily.length<120)return send(res,422,{symbol,tf,error:`Only ${daily.length} completed daily bars available.`});return send(res,200,{schema_version:1,symbol,timeframe:tf,generated_at:new Date().toISOString(),selected:{source:'yahoo-split-adjusted-server',bars:selected,n:selected.length,latest:selected.at(-1)?.date||null},daily:{source:'yahoo-split-adjusted-server',bars:daily,n:daily.length,latest:daily.at(-1)?.date||null},data_quality:{forming_bar_excluded:true,price_adjustment:'splits only; cash dividends remain in price history',volume_adjustment:'historical share volume adjusted for splits only',purpose:'technical price levels and indicators; total-return comparisons use the separate adjusted-return context endpoint'}});}catch(e){return send(res,502,{symbol,tf,error:String(e?.message||e)});}}