import {$,esc,fmt,money,pct,compact,when,pill,metric} from './ui.mjs';
import {finite} from '../src/numeric.mjs';
const ratio=x=>finite(x)?fmt(x)+'×':'—',providerPercent=x=>finite(x)?fmt(x,1)+'%':'—';
const labels={revenue:'Revenue',operating_income:'Operating income',net_income:'Net income',eps_diluted:'Diluted EPS (as filed)',operating_cash_flow:'Operating cash flow',capital_expenditure:'Capital expenditure',free_cash_flow:'Free cash flow',cash:'Cash & equivalents',long_term_debt:'Long-term debt component',short_term_debt:'Short-term debt component',assets:'Total assets',liabilities:'Total liabilities',equity:'Stockholders’ equity',shares_outstanding:'Filed common shares',gross_profit:'Gross profit',stock_compensation:'Stock compensation',revenue_growth:'Annual revenue growth',operating_margin:'Annual operating margin',net_margin:'Annual net margin'};
export function renderFundamentals(state){
  const f=state.fundamentals||{},m=f.metrics||{},s=f.summary,src=`<a href="https://tgmcharts.com" target="_blank" rel="noreferrer">Data by TGMCharts</a>`,updated=f.source_updated_at||s?.asOf?.dataUpdatedAt,old=updated&&Date.now()-Date.parse(updated)>72*3600000;
  const v=k=>m[k]?.latest?.value;
  const financialRows=Object.entries(m).map(([key,value])=>{const r=value.latest;return `<tr><td>${esc(labels[key]||key.replaceAll('_',' '))}</td><td>${r?.unit==='ratio'?pct(r.value):r?.unit==='USD/shares'?money(r.value):compact(r?.value)}</td><td>${esc(r?.unit||'')}</td><td>${esc(r?.basis||'reported')}<br>${esc(r?.period_end)}</td><td>${esc(r?.filed)}</td><td>${pill(value.classification)}<details><summary>Source</summary><span class="mini">${esc(r?.tag)} · ${esc(r?.form)} · accession ${esc(r?.accession)}${r?.derived?' · '+esc(r.derived):''}</span></details></td></tr>`;}).join('');
  $('#fundamentals').innerHTML=`<h2>Company fundamentals</h2>${pill(f.status||'UNAVAILABLE')}${old?pill('SOURCE UPDATE OLDER THAN 72H'):''}<p class="note">${s?esc(s.name)+' · '+esc(s.sector||'Sector unavailable')+' · '+esc(s.industry||'Industry unavailable')+'<br>':''}${f.status==='LOADING'?'Loading financial sources independently; technical analysis remains available.':esc(f.reason||f.provider||'No financial provider returned data.')} ${s||f.source_url?src:''}<br>Source updated ${when(updated)} · retrieved ${when(f.fetched_at)}</p>${s?`<div class="metrics">${metric('Market capitalization',compact(s.price?.marketCap)+' '+esc(s.currency||''),'Provider price date '+(s.price?.lastCloseDate||'unavailable'))}${metric('P/E · trailing',ratio(s.valuation?.peRatio),'Provider-computed TTM basis')}${metric('P/E · forward',ratio(s.valuation?.peRatioForward),'Provider estimate; not a filed fact')}${metric('Enterprise value / EBITDA',ratio(s.valuation?.evToEbitda),'Provider-computed ratio')}${metric('P/S · trailing',ratio(s.valuation?.psRatio),'Provider-computed TTM basis')}${metric('Free cash flow yield',providerPercent(s.valuation?.fcfYieldPercent),'Provider-computed')}</div>`:''}<h3>Reported financial statements</h3>${financialRows?`<div class="table-wrap"><table><thead><tr><th>Metric</th><th>Value</th><th>Unit</th><th>Basis / period end</th><th>Filed</th><th>Provenance</th></tr></thead><tbody>${financialRows}</tbody></table></div>`:'<p class="note">Filing statements unavailable for this symbol. Any sourced ratios above remain usable with their stated basis.</p>'}<p class="note">${esc(f.note||'Missing values stay unavailable.')} ${f.filing_fallback?'Some filing facts use a cached supplement, fetched '+when(f.filing_fallback.fetched_at)+'.':''}</p>${f.errors?.length?`<details><summary>Financial component availability</summary><p class="note">${f.errors.map(esc).join('<br>')}</p></details>`:''}`;
  $('#valuation').innerHTML=`<h2>Growth, profitability & financial health</h2><div class="metrics">${metric('Annual revenue growth',pct(v('revenue_growth')),'Same annual reporting periods')}${metric('Revenue CAGR · 3 years',providerPercent(s?.growthCagrPercent?.revenue?.y3),'Provider-computed annualized growth')}${metric('Gross margin · TTM',providerPercent(s?.profitability?.grossMarginPercent),'Provider-computed')}${metric('Operating margin · TTM',providerPercent(s?.profitability?.operatingMarginPercent),'Provider-computed')}${metric('Net margin · TTM',providerPercent(s?.profitability?.netMarginPercent),'Provider-computed')}${metric('ROIC',providerPercent(s?.profitability?.roicPercent),'Provider methodology; no local imputed tax')}${metric('Annual free cash flow',compact(v('free_cash_flow')),'Operating cash flow less capex; matching periods')}${metric('Current ratio',ratio(s?.financialHealth?.currentRatio),'Provider-computed')}${metric('Debt / equity',ratio(s?.financialHealth?.debtToEquity),'Provider-computed')}${metric('Interest coverage',ratio(s?.financialHealth?.interestCoverage),'Provider-computed')}${metric('Cash',compact(v('cash')),m.cash?.latest?.period_end||'Unavailable')}${metric('Dividend yield',providerPercent(s?.dividends?.yieldPercent),'Provider-computed')}</div><p class="note">${s?src+' · ':''}Financial ratios are sourced independently of the chart quote and can have different as-of dates. No intrinsic value or earnings-event timing is invented from these fields.</p>`;
  $('#catalysts').innerHTML='<h2>Catalysts & positioning</h2>'+pill('COMPONENT UNAVAILABLE')+'<p class="note">No verified earnings calendar, analyst revisions, news, options flow or insider feed was returned. These gaps do not suppress the available financial statements or technical analysis.</p>';
}
