import {$,esc,fmt,money,pct,when,pill,metric} from './ui.mjs';
import {finite} from '../src/numeric.mjs';
const table=(heads,rows)=>`<div class="table-wrap"><table><thead><tr>${heads.map(h=>`<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>'<tr>'+r.map(c=>`<td class="wrap">${c}</td>`).join('')+'</tr>').join('')}</tbody></table></div>`;
export function renderWavePanels(f,tf){
  const w=f?.wyckoff,e=f?.elliott;
  $('#wyckoff').innerHTML=`<h2>Wyckoff analysis · ${esc(tf)} <span class="tag">PRICE / VOLUME INTERPRETATION</span></h2>${pill(w?.status)} ${pill(w?.phase)}<h3>${esc(w?.bias||'Timeframe unavailable')}</h3><div class="metrics">${metric('Range support',money(w?.range?.low),w?.range?'Established '+when(w.range.known_at):'No qualifying range')}${metric('Range resistance',money(w?.range?.high),'Fixed range boundaries')}${metric('Directional invalidation',money(w?.invalidation),'Extreme supporting the current interpretation')}${metric('Measured-move objective',money(w?.objective?.price),w?.objective?.status||'Requires a confirmed range breakout')}</div><p>${esc(w?.next||'No completed data for this timeframe.')}</p>${table(['Observed event','Known at','Level','What it means'],(w?.events||[]).slice(-8).reverse().map(x=>[esc(x.type),when(x.known_at),money(x.level),esc(x.detail)]))}<details><summary>How to read Wyckoff candidates</summary><p class="note">Spring = support sweep and reclaim. Upthrust = resistance sweep and rejection. SOS / SOW = a completed range break with expanding spread and volume. LPS / LPSY = a quieter retest after that break. Phase B is range development, C is testing, D is emerging direction, E is continued movement outside the range. A full A–E sequence is not assumed.</p><p class="note">${esc(w?.note||'Insufficient data.')} ${esc(w?.objective?.basis||'')}</p></details>`;
  $('#elliott').innerHTML=`<h2>Elliott Wave scenarios · ${esc(tf)} <span class="tag">CONDITIONAL PROJECTIONS</span></h2>${pill(e?.status)}<div class="wave-cards">${(e?.candidates||[]).map((c,i)=>`<article class="trade-card"><h3>${i?'Alternative':'Primary'} · ${esc(c.degree)}</h3>${pill(c.stage)} ${pill(c.dir>0?'BULLISH PROJECTION':'BEARISH PROJECTION')}<p class="mini">Count known ${when(c.known_at)} · ${esc(c.status)}</p><div class="metrics">${metric('Count invalidation',money(c.invalidation),'Breaching this price retires this hypothesis')}${metric('Confirmation reference',money(c.confirmation),'Completed break required where applicable')}${metric('Wave 2 retracement',pct(c.retracement_2),'Of wave 1')}</div>${table(['Objective','Price','Construction','State'],c.targets.map(x=>[esc(x.name),money(x.price),esc(x.basis),pill(x.status)]))}<details><summary>Anchors and checked rules</summary>${table(['Wave','Pivot price','Pivot date','Known at'],c.anchors.map(p=>[esc(p.wave),money(p.price),when(p.ts),when(p.confirmed_ts)]))}<p class="note">${c.rules.map(esc).join(' · ')}</p></details><p class="note">${esc(c.note)}</p></article>`).join('')||'<p class="note">The confirmed swings do not currently support one of the modeled impulse counts. No count or target has been forced onto the chart.</p>'}</div><p class="note">${esc(e?.note||'This timeframe has insufficient completed bars.')}</p>`;
}
export function renderForecast(state){
  const f=state.forecast,close=state.frames['1D'].bars.at(-1)?.close,quote=state.quote?.price;
  const selectedHorizon=document.getElementById('horizon')?.value||'SWING',call=f?.calls?.[selectedHorizon];
  const callTargets=(call?.targets||[]);
  const callHtml=call?`<article class="trade-card selected forecast-call"><h3>${esc(selectedHorizon)} forecast call</h3>${pill(call.action)} ${pill(call.status)}<div class="forecast-price">${esc(call.action)}</div><div class="metrics">${metric('Entry',call.entry_zone?money(call.entry_zone.low)+'–'+money(call.entry_zone.high):'—','Forecast entry zone')}${metric('Fixed stop',money(call.stop),'Forecast invalidation')}${metric('TP1',money(callTargets[0]?.price),callTargets[0]?.basis||'No justified target')}${metric('TP2',money(callTargets[1]?.price),callTargets[1]?.basis||'—')}${metric('TP3',money(callTargets[2]?.price),callTargets[2]?.basis||'—')}${metric('Central estimate',money(call.central_estimate),call.sessions+' completed sessions')}${metric('Evidence strength',finite(call.evidence_score)?call.evidence_score+'/100':'—','Not a probability')}${metric('Live quote',money(quote),'Quote context only')}</div><p class="note">${esc(call.reason||'')}</p><p class="mini">${esc(call.invalidation||'')}</p></article>`:'';
  $('#forecast').innerHTML=`<h2>Technical price + volume forecast <span class="tag">PRICE ACTION · VOLUME · STRUCTURE · MOMENTUM</span></h2><p class="note">Origin ${when(f?.as_of)} · closing-price anchor ${money(f?.anchor_price)}${finite(quote)&&finite(close)?' · current sourced quote '+money(quote)+' ('+pct(quote/close-1)+' from anchor)':''}. The forecast call is separate from a confirmed setup and is not a calibrated probability.</p><div class="forecast-cards">${callHtml}${(f?.horizons||[]).map(h=>`<article class="trade-card"><h3>${h.sessions} trading session${h.sessions===1?'':'s'}</h3>${pill(h.status)}${finite(h.base)?`<div class="forecast-price">${money(h.base)}</div><p class="mini">Central estimate · ${pct(h.predicted_return)} from origin</p><div class="metrics">${metric('Lower scenario',money(h.bear),'Prior residual 10th percentile')}${metric('Upper scenario',money(h.bull),'Prior residual 90th percentile')}</div><div class="forecast-band"><span>Lower</span><i></i><span>Upper</span></div><p class="note">${esc(h.band_basis)}</p><details><summary>Validation and current drivers</summary>${table(['Measure','Result'],[['Training labels',String(h.training_samples)],['Labels known through',esc(h.training_label_end)],['Non-overlapping test windows',String(h.validation.n)],['Mean absolute return error',pct(h.validation.mae)],['No-change baseline error',pct(h.validation.no_change_mae)],['Historical-drift baseline error',pct(h.validation.drift_mae)],['Error improvement vs no change',pct(h.validation.mae_skill)],['Directional accuracy',pct(h.validation.directional_accuracy)+' · n='+h.validation.directional_n],['Sequential band coverage',pct(h.validation.range_coverage)+' · n='+h.validation.range_coverage_n]])}<h3>Largest model contributions</h3>${h.drivers.map(d=>`<div class="tech-line"><span>${esc(d.name)}</span><span>${fmt(d.value*100)} log-return pp</span></div>`).join('')}<p class="mini">Contributions explain this fitted model, not causation. ${h.clipped?'The raw forecast was bounded to the observed training-return range.':''}</p></details>`:`<p class="note">${esc(h.reason)}</p>`}</article>`).join('')}</div><details><summary>Forecast method, updates and limitations</summary><p class="note">${esc(f?.method||'Forecast unavailable.')}</p><p class="note">${esc(f?.update_policy||'')}</p><p class="note">${esc(f?.limitation||'')}</p></details>`;
}
